### ISSUE TITLE
Quickstart App at Step https://github.com/Urigo/Meteor-Angular2#import-angular2-into-your-app crashes while processing files with barbatus:angular2

### ISSUE THREAD

**Issue by scrapcupcake** [Urigo/Meteor-Angular2#24]
Followed the quick start to step https://github.com/Urigo/Meteor-Angular2#import-angular2-into-your-app

Launched meteor, browsed to localhost:3000, got this. Help?

Your app is crashing. Here's the latest log:

Errors prevented startup:

While processing files with barbatus:angular2 (for target os.osx.x86_64):
/tools/isobuild/compiler-plugin.js:418:13: Document sections can only be emitted to web targets
  at [object Object]._.extend.addHtml (/tools/isobuild/compiler-plugin.js:418:13)
  at [object Object]._.extend.addHtml (/tools/isobuild/compiler-plugin.js:294:24)
  at HtmlExtensionCompiler.addCompileResult (plugin/handlers/html_handler.js:60:10)
  at caching-compiler.js:305:14
  at /Users/womanpanzee/.meteor/packages/barbatus_angular2/.0.6.5.n1t2og++os+web.browser+web.cordova/plugin.HTMLBuilder.os/npm/caching-compiler/node_modules/async/lib/async.js:182:20
  at replenish (/Users/womanpanzee/.meteor/packages/barbatus_angular2/.0.6.5.n1t2og++os+web.browser+web.cordova/plugin.HTMLBuilder.os/npm/caching-compiler/node_modules/async/lib/async.js:317:21)
  at /Users/womanpanzee/.meteor/packages/barbatus_angular2/.0.6.5.n1t2og++os+web.browser+web.cordova/plugin.HTMLBuilder.os/npm/caching-compiler/node_modules/async/lib/async.js:328:15
  at Object.async.forEachLimit.async.eachLimit (/Users/womanpanzee/.meteor/packages/barbatus_angular2/.0.6.5.n1t2og++os+web.browser+web.cordova/plugin.HTMLBuilder.os/npm/caching-compiler/node_modules/async/lib/async.js:221:35)
  at HtmlExtensionCompiler.processFilesForTarget (caching-compiler.js:277:11)
  at HtmlExtensionCompiler.processFilesForTarget (plugin/compilers/ng_caching_compiler.js:15:32)
  at HtmlCompiler.processFilesForTarget (plugin/handlers/html_handler.js:34:33)

Your application has errors. Waiting for file change.

**Comment by scrapcupcake** [comment]
I'd upload a repo but it seems overly sophisticated; what I have are two files, inline, and otherwise exactly followed the quickstart, including removing the components that were suggested to remove;

index.html:
```html
<body>
<p>
  Well, here we are again
</p>
 <gbapp></gbapp>
</body>
```

app.ts:
```javascript
import {Component, View, bootstrap} from 'angular2/angular2';

@Component({
    selector: 'gbapp'
})
@View({
    template: 'Hello World!'
})
class GBApp { }

bootstrap(GBApp);
```

**Comment by barbatus** [comment]
can you please put both files to the client folder and check out if it works?

**Comment by scrapcupcake** [comment]
This fixed it! Its now producing an error for the 3 js files being loaded;

* is being assigned a //# sourceMappingURL, but already has one
Probably not a related issue, so closing this item.
