### ISSUE TITLE
Step0 in the tutorial

### ISSUE THREAD

**Issue by alsubhi** [Urigo/Meteor-Angular2#28]
I got this error when I tried to run the app just before the Templates section:

                                              
/Users/*********/.meteor/packages/meteor-tool/.1.1.10.5z7f0t++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:245
						throw(ex);
						      ^
Error: Path reservation conflict: app/client/app.js
    at Builder.reserve (/tools/isobuild/builder.js:297:15)
    at /tools/isobuild/bundler.js:1111:15
    at /tools/isobuild/bundler.js:1103:11
    at Array.forEach (native)
    at /tools/isobuild/bundler.js:1102:20
    at Array.forEach (native)
    at ClientTarget.<anonymous> (/tools/isobuild/bundler.js:1101:30)
    at ClientTarget.write (/tools/isobuild/bundler.js:1110:5)
    at /tools/isobuild/bundler.js:1847:30
    at Object.keys.forEach.subBuilder (/tools/isobuild/bundler.js:1971:9)
    at Array.forEach (native)
    at /tools/isobuild/bundler.js:1963:26
    at /tools/isobuild/bundler.js:2010:7
    at /tools/isobuild/bundler.js:2287:22
    at /tools/utils/buildmessage.js:268:13
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:261:29
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:259:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at /tools/utils/buildmessage.js:250:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:114:14)
    at Object.capture (/tools/utils/buildmessage.js:249:19)
    at Object.exports.bundle (/tools/isobuild/bundler.js:2128:31)
    at /tools/runners/run-app.js:551:36
    at time (/tools/tool-env/profile.js:232:28)
    at Function.run (/tools/tool-env/profile.js:377:12)
    at bundleApp (/tools/runners/run-app.js:541:34)
    at [object Object]._.extend._runOnce (/tools/runners/run-app.js:594:35)
    at [object Object]._.extend._fiber (/tools/runners/run-app.js:858:28)
    at /tools/runners/run-app.js:396:12

**Comment by alsubhi** [comment]
never mind it was because I created the app with name "ng" !!
